# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy ASP.Net Core app to Azure Web App - Fintechtracker

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # Build frontend
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install frontend dependencies
        run: |
          cd fintech-tracker/fintechtracker-frontend
          npm install

      - name: Build frontend
        run: |
          cd fintech-tracker/fintechtracker-frontend
          npm run build

      # Copy frontend build to backend wwwroot
      - name: Copy frontend to backend wwwroot
        run: |
          xcopy /E /I /Y fintech-tracker\fintechtracker-frontend\dist fintech-tracker\fintechtracker-backend\wwwroot

      # Build and publish backend
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "9.x"

      - name: Build backend
        run: dotnet build fintech-tracker/fintechtracker-backend/fintechtracker-backend.csproj

      - name: Publish backend
        run: dotnet publish fintech-tracker/fintechtracker-backend/fintechtracker-backend.csproj -c Release -o fintech-tracker/publish

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: fintech-tracker/publish

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID}}
          tenant-id: ${{ secrets.AZURE_TENANT_ID}}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID}}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: "Fintechtracker"
          slot-name: "Production"
          package: .
